spring.application.name=TriatlonBackend

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/triatlon_db
spring.datasource.username=root
spring.datasource.password= // Nada por lo que uso XAMPP

# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080
